// <auto-generated />
using System;
using DotNetCoreProject1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreProject1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("DotNetCoreProject1.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvailableInMarket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReviewScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("carsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableInMarket = true,
                            CarModel = "Toyota",
                            CarType = "Rav4",
                            Description = "nice car",
                            ReleaseDate = new DateTime(2021, 12, 16, 16, 17, 30, 613, DateTimeKind.Local).AddTicks(1890),
                            ReviewScore = 9.0
                        },
                        new
                        {
                            Id = 2,
                            AvailableInMarket = false,
                            CarModel = "Nissan",
                            CarType = "Rouge",
                            Description = "nice car",
                            ReleaseDate = new DateTime(2021, 12, 16, 16, 17, 30, 642, DateTimeKind.Local).AddTicks(1480),
                            ReviewScore = 8.0
                        });
                });

            modelBuilder.Entity("DotNetCoreProject1.Models.Register", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegisterId");

                    b.ToTable("usersTable");

                    b.HasData(
                        new
                        {
                            RegisterId = 1,
                            CreatedAt = new DateTime(2021, 12, 16, 16, 17, 30, 644, DateTimeKind.Local).AddTicks(8450),
                            Email = "user1@gmail.com",
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Password = "1234",
                            UpdatedAt = new DateTime(2021, 12, 16, 16, 17, 30, 644, DateTimeKind.Local).AddTicks(8480),
                            Username = "user1"
                        },
                        new
                        {
                            RegisterId = 2,
                            CreatedAt = new DateTime(2021, 12, 16, 16, 17, 30, 645, DateTimeKind.Local).AddTicks(3950),
                            Email = "user2@gmail.com",
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Password = "1234",
                            UpdatedAt = new DateTime(2021, 12, 16, 16, 17, 30, 645, DateTimeKind.Local).AddTicks(3990),
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
